### PR TITLE
update-cb3

### PR DESCRIPTION
**Pull request by ocefpaf**
@gillins I'm just testing a fresh PR... Not sure what is going on in #5

### CODE REVIEW

**Comment by ocefpaf** [comment]
I did not add the license file yet on purpose b/c I wanted to reduce the number of variables to debug this.

**Comment by ocefpaf** [comment]
@gillins I think some odd "invisible" character may have got in #5 b/c this one has  virtually the same changes (and #5 did work for me locally). Feel free to merge this if you are OK with it.

**Comment by gillins** [comment]
Thanks @ocefpaf !

**Comment by gillins** [comment]
Are there known issues with `pip` and Win/Py36?

**Comment by ocefpaf** [comment]
The error is not related to `pip` but rather a compilation error that happened before the "pip noise."

```
  Removing source in C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-_ktwu50i
Removed build tracker 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-tracker-pbwh_jp_'
Command "C:\bld\python-fmask_1540253916447\_h_env\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-_ktwu50i\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\appveyor\AppData\Local\Temp\1\pip-record-40asa2yk\install-record.txt --single-version-externally-managed --compile" failed with error code 3221225477 in C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-_ktwu50i\
Exception information:
Traceback (most recent call last):
  File "C:\bld\python-fmask_1540253916447\_h_env\lib\site-packages\pip\_internal\cli\base_command.py", line 143, in main
    status = self.run(options, args)
  File "C:\bld\python-fmask_1540253916447\_h_env\lib\site-packages\pip\_internal\commands\install.py", line 366, in run
    use_user_site=options.use_user_site,
  File "C:\bld\python-fmask_1540253916447\_h_env\lib\site-packages\pip\_internal\req\__init__.py", line 49, in install_given_reqs
    **kwargs
  File "C:\bld\python-fmask_1540253916447\_h_env\lib\site-packages\pip\_internal\req\req_install.py", line 791, in install
    spinner=spinner,
  File "C:\bld\python-fmask_1540253916447\_h_env\lib\site-packages\pip\_internal\utils\misc.py", line 705, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "C:\bld\python-fmask_1540253916447\_h_env\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-_ktwu50i\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\appveyor\AppData\Local\Temp\1\pip-record-40asa2yk\install-record.txt --single-version-externally-managed --compile" failed with error code 3221225477 in C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-_ktwu50i\
Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
```

I'm not sure what that is but sometimes using `numpy 1.14` fixed that for me.

**Comment by gillins** [comment]
That fixed it - thanks!

**Comment by ocefpaf** [comment]
> That fixed it - thanks!

No problem. I have no idea what was wrong in #5 though :-/

**Pull request merged**
