### PR TITLE
update to version 0.5.0

### PR DESCRIPTION
**Pull request by gillins**
And also update `meta.yaml` syntax to "new style"

### CODE REVIEW

**Comment by gillins** [comment]
@conda-forge-admin please rerender

**Comment by gillins** [comment]
@ocefpaf what am I doing wrong with this one? Seems like it should be something obvious...

**Comment by gillins** [comment]
@ocefpaf what am I doing wrong with this one? Seems like it should be something obvious...

**Comment by gillins** [comment]
@ocefpaf what am I doing wrong with this one? Seems like it should be something obvious...

**Comment by ocefpaf** [comment]
GitHub is flaky today so I guess e cannot do much until they are back only :-/

**Comment by gillins** [comment]
Thanks for having a look. Works for me locally too....

**Comment by gillins** [comment]
See #6

**Pull request closed without merging**
